# Generated by Django 5.1.2 on 2024-10-20 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
                'verbose_name_plural': 'Модели ведущих мостов',
            },
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
                'verbose_name_plural': 'Модели двигателей',
            },
        ),
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Узел отказа',
                'verbose_name_plural': 'Узлы отказа',
            },
        ),
        migrations.CreateModel(
            name='OrganizationOfMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Организация, проводившая ТО',
                'verbose_name_plural': 'Организации, проводившие ТО',
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ востановления',
                'verbose_name_plural': 'Способы востановления',
            },
        ),
        migrations.CreateModel(
            name='SteeringAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
                'verbose_name_plural': 'Модели управляемых мостов',
            },
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
                'verbose_name_plural': 'Модели трансмиссий',
            },
        ),
        migrations.CreateModel(
            name='TypeOfMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид ТО',
                'verbose_name_plural': 'Виды ТО',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель техники',
                'verbose_name_plural': 'Модели техники',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumberCar', models.CharField(max_length=10, unique=True, verbose_name='Зав. № машины')),
                ('serialNumberEngine', models.CharField(max_length=10, verbose_name='Зав № двигателя')),
                ('serialNumberTransmission', models.CharField(max_length=10, verbose_name='Зав. № трансмиссии')),
                ('serialNumberDriveAxle', models.CharField(max_length=10, verbose_name='Зав № ведущего моста')),
                ('serialNumberSteeringAxle', models.CharField(max_length=10, verbose_name='Зав № управляемого моста')),
                ('supplyContract', models.CharField(max_length=20, verbose_name='Договор поставки №, дата')),
                ('shippingDate', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=300, verbose_name='Грузополучатель (конечный потребитель)')),
                ('deliveryAddress', models.CharField(max_length=300, verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.CharField(max_length=20, verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clientprofile', verbose_name='Клиент')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.servicecompanyprofile', verbose_name='Сервисная компания')),
                ('driveAxleModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.driveaxlemodel', verbose_name='Модель ведущего моста')),
                ('engineModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.enginemodel', verbose_name='Модель двигателя')),
                ('steeringAxleModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.steeringaxlemodel', verbose_name='Модель управляемого моста')),
                ('transmissionModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.transmissionmodel', verbose_name='Модель трансмиссии')),
                ('vehicleModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.vehiclemodel', verbose_name='Модель техники')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfRefusal', models.DateField(verbose_name='Дата отказа')),
                ('operatingTime', models.CharField(max_length=20, verbose_name='Наработка, м/час')),
                ('descriptionOfFailure', models.TextField(verbose_name='Описание отказа')),
                ('sparePartsUsed', models.TextField(verbose_name='Используемые запасные части')),
                ('restoreDate', models.DateField(verbose_name='Дата восстановления')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Машина')),
                ('failureNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.failurenode', verbose_name='Узел отказа')),
                ('recoveryMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.recoverymethod', verbose_name='Способ восстановления')),
            ],
            options={
                'verbose_name': 'Рекламации',
                'verbose_name_plural': 'Рекламации',
                'ordering': ['-dateOfRefusal'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataOfMaintenance', models.DateField(verbose_name='Дата проведения ТО')),
                ('operatingTime', models.CharField(max_length=20, verbose_name='Наработка, м/час')),
                ('workOrderNumber', models.CharField(max_length=20, verbose_name='№ заказ-наряда')),
                ('workOrderDate', models.DateField(verbose_name='Дата заказ-наряда')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Машина')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.servicecompanyprofile', verbose_name='Сервисная компания')),
                ('organizationOfMaintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.organizationofmaintenance', verbose_name='Организация, проводившая ТО')),
                ('typeOfMaintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.typeofmaintenance', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'ТО',
                'verbose_name_plural': 'ТО',
                'ordering': ['-dataOfMaintenance'],
            },
        ),
    ]
